// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCTdhzpJJr4iwFuNNcWqisvQmwZuoMqw',
    appId: '1:285114139955:web:a36ee61f089453fe49aa46',
    messagingSenderId: '285114139955',
    projectId: 'linkedin-a2769',
    authDomain: 'linkedin-a2769.firebaseapp.com',
    storageBucket: 'linkedin-a2769.firebasestorage.app',
    measurementId: 'G-QX38D939DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIwgPe0EnYCIUhTlyJME-iipM4lglCNJk',
    appId: '1:285114139955:android:6fb78c18a218f4fb49aa46',
    messagingSenderId: '285114139955',
    projectId: 'linkedin-a2769',
    storageBucket: 'linkedin-a2769.firebasestorage.app',
  );
}
